### ISSUE TITLE
Allow user to control how the top 5 urls are selected.

### ISSUE THREAD

**Issue by hhellyer** [RuntimeTools/graphmetrics#33]
At the moment the top 5 response times is always top 5 average response times.
This does not work well as infrequently accessed paths can occupy the top spaces on the list permanently. It doesn't necessarily show useful information about what your application spends its time doing.

It would be useful to be able to show the top 5 urls by:
- Average (mean) response time.
- Total request response time.
- Total request count.
- Mean response time of the top 5 most requested urls. (?)

These would let the user see which requests were slowest, which requests were most common, which requests were taking most of the time and how long it was taking to respond to the most frequent requests.

We will need some sort of control on the top 5 urls chart to let the user select between these.

**Comment by robbinspg** [comment]
Does https://github.com/RuntimeTools/graphmetrics/pull/38 address this issue? The HTTP Summary table is sortable by column and can replace the "Top 5"

**Comment by james-wallis** [comment]
We've created a HTTP Summary table which allows sorting and is in use over the top5 box. As such we will close this issue as top5 is being dropped from usage.
